import fs from "node:fs/promises";
import path from "node:path";
import { execFileSync } from "node:child_process";
import { compile } from "json-schema-to-typescript";
import Ajv from "ajv";
import standaloneCode from "ajv/dist/standalone/index.js";
const index = process.argv.indexOf("--native");
const native =
  index < 0
    ? process.env.PROJECT_NATIVE_ROOT &&
      path.join(process.env.PROJECT_NATIVE_ROOT, "examples/contracts")
    : process.argv[index + 1];
if (!native)
  throw new Error(
    "Pass --native with the freshly built contracts executable. No cached executable is selected.",
  );
const schemas = JSON.parse(
  execFileSync(native, ["schemas"], { encoding: "utf8" }),
);
const ajv = new Ajv({
  allErrors: true,
  strict: false,
  formats: { uint32: true, uint64: true, uint: true, double: true },
  code: { source: true, esm: true },
});
const types = [];
for (const [name, schema] of Object.entries(schemas)) {
  schema.$id = name;
  ajv.addSchema(schema, name);
  types.push(
    await compile(schema, schema.title, {
      bannerComment:
        "/* Generated by web/contracts.mjs. Edit the Rust contracts. */",
      additionalProperties: true,
    }),
  );
}
const outputs = {
  "contracts.schema.json": JSON.stringify(schemas, null, 2) + "\n",
  "contracts.d.ts": types.join("\n"),
  "validators.mjs":
    standaloneCode(
      ajv,
      Object.fromEntries(Object.keys(schemas).map((k) => [k, k])),
    ) + "\n",
  "validators.d.mts":
    Object.keys(schemas)
      .map((k) => `export function ${k}(value: unknown): boolean;`)
      .join("\n") + "\n",
};
const folder = new URL("./src/generated/", import.meta.url);
await fs.mkdir(folder, { recursive: true });
for (const [name, bytes] of Object.entries(outputs)) {
  const file = new URL(name, folder);
  if (process.argv.includes("--check")) {
    if ((await fs.readFile(file, "utf8").catch(() => "")) !== bytes)
      throw new Error(
        `Contract drift: regenerate ${name} using the checked-out Rust engine.`,
      );
  } else await fs.writeFile(file, bytes);
}
